### ISSUE TITLE
Get rid of dependency ranges?

### ISSUE THREAD

**Issue by nidi3** [nidi3/raml-tester#59]

**Comment by ddossot** [comment]
Yes please :+1:

**Comment by NoOrdInaryGuy** [comment]
Nice, I was just about to open a PR about this! :-)

I was having some issues due to this (very long standing) Maven issue: https://issues.apache.org/jira/browse/MNG-3092 , where I was having SNAPSHOT's of the jackson libraries pulled in.

Currently having to manually exclude the Jackson libraries and include 2.6.3 , so would love to see this change in a release!

**Comment by nidi3** [comment]
Whoa, what an issue! 8 years and still discussing :-1:
